{
    "name": "Sistema de Gestión de Datos Técnicos -  SIGEDAT EAAB",
    "version": "1.0",
    "depends": [
        'base',
        'mail',
        'base_conf',
        'web',
    ],
    "author": "Linktic",
    "category": "Datos Técnicos",
    'data': [
        'security/security.xml',
        "security/ir.model.access.csv",
        "views/sigedat_grupo_views.xml",
        "views/sigedat_persona_views.xml",
        "views/sigedat_equipo_apoyo_views.xml",
        "views/sigedat_persona_tipo_identificacion_views.xml",
        "views/sigedat_revisor_no_disponibilidad_views.xml",
        "views/sigedat_revisor_views.xml",
        "views/sigedat_documento_views.xml",
        "views/sigedat_documento_tipo_extension_views.xml",
        "views/sigedat_documento_tipo_views.xml",
        "views/sigedat_carpeta_views.xml",
        "views/sigedat_cita_views.xml",
        "views/sigedat_cita_tipo_views.xml",
        "wizards/agregar_contacto_view.xml",
        "wizards/agendar_cita_view.xml",
        "wizards/subir_documento_view.xml",
        "wizards/asignar_revisor_view.xml",
        "wizards/devolver_tramite_view.xml",
        "views/sigedat_tramite_solicitud_views.xml",
        "views/sigedat_tramite_cuadro_maestro_views.xml",
        "views/sigedat_tramite_tipo_bloque_atencion_views.xml",
        "views/sigedat_tramite_tipo_views.xml",
        "views/sigedat_frente_views.xml",
        "wizards/agregar_persona_view.xml",
        "wizards/iniciar_solicitud_view.xml",
        "wizards/crear_contrato_view.xml",
        "wizards/configuracion_general_view.xml",
        "wizards/mostrar_mensaje_view.xml",
        "wizards/crear_soporte_view.xml",
        "wizards/observacion_relacionada_view.xml",
        "views/sigedat_tramite_contacto_views.xml",
        "views/sigedat_tramite_views.xml",
        "views/sigedat_contrato_tipo_views.xml",
        "views/sigedat_contrato_views.xml",
        "views/sigedat_area_views.xml",
        "views/sigedat_lista_chequeo_views.xml",
        "views/sigedat_lista_chequeo_seccion_views.xml",
        "views/sigedat_lista_chequeo_item_views.xml",
        "views/sigedat_lista_chequeo_item_observacion_views.xml",
        "views/sigedat_lista_chequeo_item_observacion_soporte_views.xml",
        "views/menus.xml",
        "views/template.xml",
        "data/plantilla_pagina.xml",
        "data/plantilla_reporte.xml",
        "data/plantilla_correo.xml",
        "data/cron.xml",
        "data/secuencia.xml",
    ],
    'test': [
    ],
    'demo': [
    ],
    'external_dependencies': {
        'python': [
            'appy',
            'workalendar',
        ]
    },
    'installable': True,
    'description': """
        Módulo para la Gestión de los Datos Técnicos del EAAB
        """,
    "license":"LGPL-3",
}
