from . import sigedat_grupo
from . import sigedat_equipo_apoyo
from . import sigedat_persona
from . import sigedat_persona_tipo_identificacion
from . import sigedat_revisor_no_disponibilidad
from . import sigedat_revisor
from . import sigedat_documento
from . import sigedat_documento_tipo_extension
from . import sigedat_documento_tipo
from . import sigedat_carpeta
from . import sigedat_cita
from . import sigedat_cita_tipo
from . import sigedat_tramite_solicitud_cartesianas
from . import sigedat_tramite_solicitud
from . import sigedat_tramite_tipo_bloque_atencion
from . import sigedat_tramite_tipo
from . import sigedat_frente
from . import sigedat_tramite
from . import sigedat_contrato_tipo
from . import sigedat_contrato
from . import sigedat_area
from . import sigedat_lista_chequeo
from . import sigedat_lista_chequeo_seccion
from . import sigedat_lista_chequeo_item
from . import sigedat_lista_chequeo_item_observacion
from . import sigedat_lista_chequeo_item_observacion_soporte
from . import sigedat_tramite_contacto
from . import sigedat_tramite_cuadro_maestro